[package]
name = "libnfs"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
description = "libnfs bindings allow you to create nfs mounts in memory/userspace"
homepage = "https://github.com/cholcombe973/libnfs"
repository = "https://github.com/cholcombe973/libnfs"
documentation = "https://docs.rs/libnfs"
license = "MIT"
readme = "README.md"
keywords = ["nfs"]
categories = ["api-bindings", "network-programming", "filesystem", "external-ffi-bindings"]
edition = '2018'


[dependencies]
futures = "0.1.25"
libc = "~0.2"
libnfs-sys = "~0.2"
log = "~0.4"
mio = "~0.6"
nix = "~0.11"
tokio = "~0.1"