name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    branches: [ "*" ]
    inputs:
      name:
        description: "manual run"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: sudo apt-get install -y libkrb5-dev
    - name: Clone libnfs
      uses: actions/checkout@v4
      with:
        repository: cwedgwood/libnfs
        path: libnfs/
        ref: master
    - name: Build and install libnfs (working in libnfs/)
      run: |
        cd libnfs/
        ./bootstrap
        ./configure
        make -j4
        sudo make install
    - name: 'Checkout (of this "rs-libnfs" repo)'
      uses: actions/checkout@v4
    - name: Build rs-libnfs
      run:  cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
